"""nav_manifest generates docs/javascripts/nav-data.js from front-matter.

Mirrors test_generate_build.py's style: a throwaway repo fixture rather than
scanning the real docs/ tree, so the tests stay independent of playbook
content. A separate check against the real tree (b) confirms a known page.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

import nav_manifest

ROOT = Path(__file__).resolve().parents[1]

JWT_PAGE = """---
title: JWT
module: authentication
status: reviewed
tags: [Authentication]
---

# JWT
"""

INDEX_PAGE = """---
title: Home
module: root
status: draft
tags: [Overview]
---

# Home
"""

STUB_PAGE = """# No front-matter here
"""


def run(repo: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True, text=True)


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    run(tmp_path, "init", "-q", "-b", "main")
    docs = tmp_path / "docs"
    (docs / "modules" / "authentication").mkdir(parents=True)
    (docs / "index.md").write_text(INDEX_PAGE, encoding="utf-8")
    (docs / "modules" / "authentication" / "jwt.md").write_text(JWT_PAGE, encoding="utf-8")
    (docs / "modules" / "authentication" / "legacy.md").write_text(STUB_PAGE, encoding="utf-8")
    return tmp_path


def _parse_manifest(text: str) -> dict:
    assert text.startswith("// Generated by tools/nav_manifest.py — do not edit.\n")
    body = text.split("\n", 1)[1]
    prefix = "window.__navStatus = "
    assert body.startswith(prefix)
    assert body.rstrip().endswith(";")
    json_text = body[len(prefix) :].rstrip()[: -len(";")]
    return json.loads(json_text)


def test_manifest_is_valid_json_after_stripping_wrapper(repo):
    manifest = nav_manifest.collect(repo / "docs")
    text = nav_manifest.render(manifest)
    parsed = _parse_manifest(text)
    assert parsed == manifest


def test_totals_equal_sum_over_pages(repo):
    manifest = nav_manifest.collect(repo / "docs")
    counted = {"stub": 0, "draft": 0, "reviewed": 0}
    for status in manifest["pages"].values():
        counted[status] += 1
    counted["total"] = sum(counted.values())
    assert manifest["totals"] == counted


def test_missing_or_invalid_status_counts_as_stub(repo):
    manifest = nav_manifest.collect(repo / "docs")
    assert manifest["pages"]["modules/authentication/legacy"] == "stub"
    assert manifest["totals"]["stub"] == 1


def test_section_counts_are_recursive_and_root_excluded(repo):
    manifest = nav_manifest.collect(repo / "docs")
    assert "" not in manifest["sections"]
    assert manifest["sections"]["modules/authentication"] == {
        "stub": 1,
        "draft": 0,
        "reviewed": 1,
        "total": 2,
    }


def test_generator_writes_expected_file_and_is_idempotent(repo):
    exit_code = nav_manifest.main(["--root", str(repo)])
    assert exit_code == 0
    out_path = repo / "docs" / "javascripts" / "nav-data.js"
    first = out_path.read_text(encoding="utf-8")
    assert _parse_manifest(first) == nav_manifest.collect(repo / "docs")

    exit_code = nav_manifest.main(["--root", str(repo)])
    assert exit_code == 0
    assert out_path.read_text(encoding="utf-8") == first


def test_invalid_yaml_front_matter_exits_nonzero(tmp_path):
    docs = tmp_path / "docs"
    docs.mkdir()
    (docs / "broken.md").write_text("---\nstatus: [unclosed\n---\n\n# Broken\n", encoding="utf-8")
    assert nav_manifest.main(["--root", str(tmp_path)]) == 1


def test_known_real_page_is_present_and_reviewed():
    """docs/modules/authentication/jwt.md is a real, reviewed page."""
    manifest = nav_manifest.collect(ROOT / "docs")
    assert manifest["pages"]["modules/authentication/jwt"] == "reviewed"
