"""Generate the build-time navigation status manifest.

Scans every `docs/**/*.md` file's front-matter for its `status` field and
writes `docs/javascripts/nav-data.js`: a static JS asset that exposes
`window.__navStatus` (per-page status, per-section rollups, and repo-wide
totals) so the site's client-side nav can render status badges without a
server round-trip.

Like the other build-time pages in `generate.py build`, the output is a
gitignored artifact derived from committed sources (front-matter), never
committed itself.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

STATUSES = ("stub", "draft", "reviewed")
DEFAULT_STATUS = "stub"

HEADER = "// Generated by tools/nav_manifest.py — do not edit.\n"


class FrontMatterError(Exception):
    """Raised when a page's front-matter cannot be parsed as YAML."""


def _split_front_matter(text: str) -> str | None:
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 3)
    if end == -1:
        return None
    return text[4:end]


def page_status(path: Path) -> str:
    """Return `path`'s front-matter status, or "stub" if missing/invalid.

    Raises FrontMatterError if the front-matter block is present but is
    not valid YAML; that is a build error, not a missing-status default.
    """
    text = path.read_text(encoding="utf-8")
    raw = _split_front_matter(text)
    if raw is None:
        return DEFAULT_STATUS
    try:
        data = yaml.safe_load(raw)
    except yaml.YAMLError as error:
        raise FrontMatterError(f"{path}: invalid YAML front-matter: {error}") from error
    if not isinstance(data, dict):
        return DEFAULT_STATUS
    status = data.get("status")
    return status if status in STATUSES else DEFAULT_STATUS


def page_key(docs_dir: Path, file: Path) -> str:
    relative = file.relative_to(docs_dir).as_posix()
    return relative[: -len(".md")]


def collect(docs_dir: Path) -> dict:
    """Build the manifest: per-page status, per-section rollups, totals."""
    files = sorted(docs_dir.rglob("*.md"))

    pages: dict[str, str] = {}
    page_dir: dict[str, str] = {}
    for file in files:
        key = page_key(docs_dir, file)
        pages[key] = page_status(file)
        parent = file.parent.relative_to(docs_dir).as_posix()
        page_dir[key] = "" if parent == "." else parent

    # A section is every directory that *directly* contains at least one
    # .md file (root excluded). Its counts are recursive: every page whose
    # directory is the section itself or a descendant of it.
    direct_dirs = sorted({d for d in page_dir.values() if d})

    sections: dict[str, dict[str, int]] = {}
    for section_dir in direct_dirs:
        counts = {status: 0 for status in STATUSES}
        for key, status in pages.items():
            page_d = page_dir[key]
            if page_d == section_dir or page_d.startswith(section_dir + "/"):
                counts[status] += 1
        counts["total"] = sum(counts[status] for status in STATUSES)
        sections[section_dir] = counts

    totals = {status: 0 for status in STATUSES}
    for status in pages.values():
        totals[status] += 1
    totals["total"] = sum(totals[status] for status in STATUSES)

    return {
        "pages": dict(sorted(pages.items())),
        "sections": dict(sorted(sections.items())),
        "totals": totals,
    }


def render(manifest: dict) -> str:
    body = json.dumps(manifest, indent=2, sort_keys=True)
    return f"{HEADER}window.__navStatus = {body};\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="nav_manifest")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args(argv)

    root: Path = args.root.resolve()
    docs_dir = root / "docs"

    try:
        manifest = collect(docs_dir)
    except FrontMatterError as error:
        print(str(error), file=sys.stderr)
        return 1

    out_path = docs_dir / "javascripts" / "nav-data.js"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(render(manifest))

    print(f"wrote: {out_path.relative_to(root).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
